variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - generate_javascript
  - test_javascript
  - test_python_and_upload

generate_javascript:
  stage: generate_javascript
  image: git.vro.life/vro/dependency_proxy/containers/python:3.6
  artifacts:
    paths:
      - .js
  script:
    - mkdir .js
    - python test_js.py ./.js
    - cp tests.mjs ./.js

test_javascript:
  stage: test_javascript
  image: git.vro.life/vro/dependency_proxy/containers/node:14
  script:
    - (cd .js && node tests.mjs)

test_python_and_upload:
  stage: test_python_and_upload
  image: git.vro.life/vro/dependency_proxy/containers/python:3.6
  script:
    - python -V
    - python -m unittest tests.py
    - python setup.py bdist_wheel --build-number ${CI_PIPELINE_IID}
    - pip install twine
    - export TWINE_PASSWORD=${CI_JOB_TOKEN} 
    - export TWINE_USERNAME=gitlab-ci-token 
    - python -m twine upload --repository-url https://pypi.vro.life dist/*
