image: python:3.6

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  
run:
  script:
    - python -m unittest
    - python setup.py sdist bdist_wheel
    - pip install twine
    - export TWINE_PASSWORD=${CI_JOB_TOKEN} 
    - export TWINE_USERNAME=gitlab-ci-token 
    - python -m twine upload --repository-url git.vro.life/pkg/pypi dist/*
    
